name: FOSSASIA Continuous Deployment (CD)
on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on:
      - ubuntu-latest
    env:
      SERVICE_NAME: ghcr.io/chamodshehanka/fossasia-summit-2023
      CONTAINER_REGISTRY: ghcr.io
      DEPLOYMENT_MANIFEST_PATH: ./k8s/deployment.yaml
    steps:
      - uses: actions/checkout@v3
      # - name: Set Version
      #   id: event-version
      #   run: echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build the Docker image
        run: docker build -t $SERVICE_NAME:latest .
      - name: GitHub Image Push
        run: docker push $SERVICE_NAME:latest
      - name: Set K8s context
        uses: azure/k8s-set-context@v2
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
      - name: Deploy to GKE
        run: | 
          kubectl apply -f ${{ env.DEPLOYMENT_MANIFEST_PATH }}